import "./globals.css";
import "./responsive.css";
import "./style.css";
import "./bootstrap.css";
import variables from "./variables.module.scss";
// import { ThemeProvider } from "@material-tailwind/react";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <ThemeProvider> */}
      <body className={inter.className}>{children}</body>
      {/* </ThemeProvider> */}
    </html>
  );
}
